# Generated by Django 5.2.8 on 2026-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11, null=True, unique=True)),
                ('birthday', models.DateField()),
                ('url_photo', models.CharField(null=True)),
                ('document', models.CharField(null=True)),
                ('banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
