# Generated by Django 5.2.8 on 2026-01-21 13:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, null=True, unique=True)),
                ('birthday', models.DateField()),
                ('url_photo', models.CharField()),
                ('document', models.CharField()),
                ('banned', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField()),
                ('product_type', models.CharField(choices=[('TICKET', 'Ticket'), ('CONSUMER', 'Consumer')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('qtd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('id_banned', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Banido'), ('REVOKED', 'Revogado'), ('FINISHED', 'Concluido')], default='ACTIVE', max_length=20)),
                ('cause', models.CharField()),
                ('date_ban', models.DateTimeField()),
                ('expire_in', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='ingresso.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cpf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='ingresso.clients')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consumers_Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('CANCELED', 'Cancelado'), ('REFUNDED', 'Reembolsado'), ('PARTICIALLY_REFUNDED', 'Parcialmente Reembolsado')], default='PENDING', max_length=20)),
                ('pay_method', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumers_Orders_Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumers_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ingresso.consumers_orders')),
                ('product_id', models.ForeignKey(limit_choices_to={'type': 'CONSUMER'}, on_delete=django.db.models.deletion.CASCADE, to='ingresso.product')),
            ],
        ),
        migrations.CreateModel(
            name='Revocation_requests',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Em analise'), ('REQUESTED', 'Solicitação'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='REQUESTED', max_length=20)),
                ('justification', models.CharField()),
                ('date_request', models.DateTimeField(auto_now_add=True)),
                ('date_conclusion', models.DateTimeField()),
                ('admin_response', models.CharField()),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='ingresso.clients')),
                ('id_banned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banneds', to='ingresso.banned')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('CANCELED', 'Cancelado'), ('REFUNDED', 'Reembolsado'), ('PARTICIALLY_REFUNDED', 'Parcialmente Reembolsado')], default='PENDING', max_length=50)),
                ('pay_method', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Order_Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(limit_choices_to={'product_type': 'TICKET'}, on_delete=django.db.models.deletion.PROTECT, to='ingresso.product')),
                ('ticket_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='ingresso.ticket_orders')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('used_in', models.DateTimeField()),
                ('validity', models.DateTimeField()),
                ('status', models.CharField(choices=[('VALID', 'Válido'), ('USED', 'Usado'), ('CANCELED', 'Cancelado'), ('TRANSFERRED', 'Transferido')], default='VALID', max_length=20)),
                ('token', models.CharField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.clients', to_field='cpf')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ingresso.ticket_orders')),
            ],
        ),
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('used_in', models.DateTimeField()),
                ('validity', models.DateTimeField()),
                ('status', models.CharField(choices=[('VALID', 'Válido'), ('USED', 'Usado'), ('CANCELED', 'Cancelado'), ('TRANSFERRED', 'Transferido')], default='VALID', max_length=20)),
                ('token', models.CharField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_orders', to='ingresso.consumers_orders')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresso.clients', to_field='cpf')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
