# Generated by Django 5.2.8 on 2026-01-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='document',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='url_photo',
            field=models.CharField(null=True),
        ),
    ]
